Add checks of requirements

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,6 +8,18 @@ EPOCH=$(date +%s%N)
 ARCHIVE=$DOT_FILES/archive/$EPOCH
 NERD_FONT_VERSION="3.1.1"
 TMUX_VERSION="3.4"
+REQUIREMENTS=(sudo curl make unzip)
+
+# Check if commands exist
+function check_commands {
+    local commands=("$@")
+    for cmd in "${commands[@]}"; then
+        if ! command -v "$cmd" &> /dev/null; then
+            echo "$cmd could not be found"
+            exit 1
+        fi
+    done
+}
 
 function init {
 	# Check machine
@@ -26,6 +38,7 @@ function init {
 		echo "$machine is not added yet"
 		exit 1
 	fi
+  check_commands "${REQUIREMENTS[@]}"
 }
 function confirm {
 	read -r -p "${1:-Are you sure? [y/N]} " response
